"""Filesystem path constants for this project.

Every path is derived from this file's own location (not hardcoded), so the
project works no matter where the repo is checked out -- see
`previous_work/scripts/common/io_utils.py` for the convention this follows.
Notebooks should import from here instead of hand-typing "../data/..." strings.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"

# The one RO-Crate release currently under data/. If/when a second release is
# added, give it its own CRATE_DIR constant rather than repointing this name.
CRATE_DIR = DATA_DIR / "2026-06_mistral-small3.1-24b"

CRATE_METADATA_JSON = CRATE_DIR / "ro-crate-metadata.json"
CRATE_README = CRATE_DIR / "README.md"

CRATE_INPUTS_DIR = CRATE_DIR / "inputs"
CRATE_RESULTS_DIR = CRATE_DIR / "results"
CRATE_CONFIG_DIR = CRATE_DIR / "config"
CRATE_ONTOLOGY_DIR = CRATE_DIR / "ontology"
CRATE_LOGS_DIR = CRATE_DIR / "logs"
CRATE_PROVENANCE_DIR = CRATE_DIR / "provenance"

RUN_INDEX_TSV = CRATE_PROVENANCE_DIR / "run_index.tsv"
RUN_SEGMENTS_TSV = CRATE_PROVENANCE_DIR / "run_segments.tsv"
CHECKSUMS_SHA256 = CRATE_PROVENANCE_DIR / "checksums.sha256"

# Artifacts this project computes from the crate (not part of the crate itself) -- e.g. the
# full-scale trace-back check, which takes too long to recompute on every notebook run.
DERIVED_DIR = DATA_DIR / "derived"
TRACE_BACK_FULL_PARQUET = DERIVED_DIR / "trace_back_full.parquet"
# Same schema/row-count as TRACE_BACK_FULL_PARQUET, but with every value the LLM stages resolved
# folded in (strategy/raw_fields/... replaced in place) -- see build_trace_back_full_with_llm.py.
TRACE_BACK_FULL_WITH_LLM_PARQUET = DERIVED_DIR / "trace_back_full_with_llm.parquet"

# Small, git-committed reference data the notebooks depend on: frozen historical samples that
# can't be recomputed from the crate alone. Unlike DATA_DIR (gitignored, holds the large downloaded
# RO-Crate and its regenerable derived artifacts), these are tiny and one-of-a-kind, so they're
# checked into the repo instead.
NOTEBOOK_FIXTURES_DIR = PROJECT_ROOT / "notebooks" / "fixtures"

# A reproducible n=400 sample of DISTINCT (target_field, target_value) patterns from the
# deterministic "not found" residual, drawn before any LLM pass runs -- built by
# `sample_provenance_benchmark.py` with a committed, fixed seed. One row per pattern; one accession
# chosen uniformly at random among that pattern's occurrences (accessions are NOT required to be
# unique across the 400 -- a common pattern can legitimately be unresolved on hundreds of accessions).
PROVENANCE_BENCHMARK_400_PARQUET = (
    NOTEBOOK_FIXTURES_DIR / "provenance_benchmark_400.parquet"
)

# Results of Benchmark A: the raw per-chunk Claude Opus 5 annotation (`chunk_*.verdicts.json`,
# see `build_benchmark_annotation_chunks.py`), each Qwen model's two-condition run (see
# `run_provenance_benchmark_qwen.py`), and the merged/scored tables `score_provenance_benchmark.py`
# computes from them. Checked into the repo like the sample above -- the Claude annotation in
# particular can't be regenerated by any script (it came from a one-off interactive review).
PROVENANCE_BENCHMARK_400_RESULTS_DIR = (
    NOTEBOOK_FIXTURES_DIR / "provenance_benchmark_400_results"
)

# Per-BioSample metadata (submission/publication dates, primary BioProject, owner lab) that
# isn't in trace_back_full.parquet -- built once by `biosample_metadata.py` from a full scan of
# `inputs/`, and stable across trace-back re-runs (unlike trace_back_full.parquet, this doesn't
# change as the trace-back job progresses, so it never needs rebuilding once it exists).
BIOSAMPLE_METADATA_PARQUET = DERIVED_DIR / "biosample_metadata.parquet"

# Independent cross-check of the deterministic cascade's non-exact strategies (normalized,
# case-insensitive, ontology synonym, fuzzy, bag of words) against EBI Zooma: every distinct
# (raw_field, raw_matched_phrase, assigned_term_id) case those strategies produced, and Zooma's
# own text-annotation verdict for each distinct evidence phrase. See run_zooma_batch.py.
ZOOMA_CASE_UNIVERSE_PARQUET = DERIVED_DIR / "zooma_case_universe.parquet"
ZOOMA_RESULTS_JSONL = DERIVED_DIR / "zooma_results.jsonl"
ZOOMA_FAILED_BATCHES_JSONL = DERIVED_DIR / "zooma_failed_batches.jsonl"
